# Give the Container Builder service account "Cloud Functions Developer" access

steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
  dir: 'functions/autodeploy'
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['auth', 'list']
  dir: 'functions/autodeploy'
- name: 'gcr.io/cloud-builders/npm'
  args: ['test']
  dir: 'functions/autodeploy'
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'functions', 'deploy', 'helloGET', '--trigger-http']
  dir: 'functions/autodeploy'
